version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @ angular/cli@15.2.8
    build:
      commands:
        - echo "Building Angular project..."
        - ng build --configuration production
      post_build:
        commands:
          - echo "Updating files in the S3 bucket..."
          - aws s3 sync dist/online-course-platform-frontend/ s3://course-platform-ngcode --delete
